[project]
name = "walkthru-weather-index"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.59",
    "dask[distributed]>=2026.1.2",
    "duckdb==1.5.0.dev329",
    "h3>=4.0",
    "h5netcdf>=1.8.1",
    "h5py>=3.15.1",
    "huggingface-hub>=1.5.0",
    "matplotlib>=3.10.8",
    "netcdf4>=1.7.4",
    "numpy>=2.4.2",
    "odc-stac>=0.5.2",
    "pandas>=3.0.1",
    "planetary-computer>=1.0.0",
    "pyarrow>=23.0.1",
    "pystac-client>=0.9.0",
    "s3fs>=0.4.2",
    "scipy>=1.17.1",
    "xarray>=2026.2.0",
]

[project.optional-dependencies]
gpu = [
    "cupy-cuda12x>=13.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "ruff>=0.15.4",
]
